"""
Schedule K-1 cross-partner test profiles (Profiles 11-34).

Designed to exercise cross-partner and multi-year validation rules:

Group 1 — Same-partnership partners (Category A tests):
  11 -- Sunbelt Retail RE Fund II (2nd LP, 5.00%)
  12 -- Sunbelt Retail RE Fund II (GP, 1.00%)
  13 -- Pacific Coast Orthopedic Partners (2nd GP, 16.67%)
  14 -- Pacific Coast Orthopedic Partners (3rd GP, 85.00% — INVALID, triggers A1)

Group 2 — Prior-year K-1s (Category B tests):
  15 -- Sunbelt Retail RE Fund II, Okonkwo 2023 (valid B1 continuity)
  16 -- Granite Peak Venture III, Nambiar 2023 (invalid B1 — capital mismatch)
  17 -- Stonebridge Offshore Macro, Vanhanen 2023 (valid B1 + invalid B4 — GP→LP type change)

Group 3 — Edge cases:
  18 -- Sunbelt Retail RE Fund II, Morales 2023 (prior-year for Profile 11)

Group 4 — Additional partners for single-partner partnerships (2 each):
  19-20 -- Granite Peak Venture III (LP 8%, LP 5%)
  21-22 -- Stonebridge Offshore Macro (GP fund manager 15%, LP 2%)
  23-24 -- Ironclad Industrial Buyout IV (LP 3.75%, GP 1.00%)
  25-26 -- Red Mesa Royalties (LP 10%, LP 8% — triggers D1 distributions > 3x)
  27-28 -- Nakamura Family Investment (LP 22.50%, GP managing member 10%)
  29-30 -- Sunbelt CRE Opportunity III (LP 3.20%, GP 1.50%)
  31-32 -- Cascadia Clean Energy (LP 8%, LP 6% — LP has SE earnings, triggers D4)
  33-34 -- Southern Hospitality Restaurant (LP 25%, LP 15% — sum=75% triggers A2 warning)

All EINs, SSNs, addresses, and financial figures are entirely fictitious.
"""

CROSS_PARTNER_PROFILES = [
    # =========================================================================
    # PROFILE 11 — Sunbelt Retail Real Estate Fund II, LP
    # Second LP in the same partnership as Profile 1 (Okonkwo).
    # Tests A2 (sum=8.50% < 100%), A3 (income proportionality).
    # EIN matches Profile 1: 46-3819204
    # =========================================================================
    {
        "profile_number": 11,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Sunbelt Retail Real Estate Fund II, LP",
        "partnership_address": "3200 Southwest Freeway, Suite 1800\nHouston, TX 77027",
        "irs_center": "Ogden, UT",
        "ein": "46-3819204",
        "partner_name": "David K. Morales",
        "partner_address": "8901 Preston Road, Apt 2204\nDallas, TX 75225",
        "ssn": "453-18-7692",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "5.00",
        "loss_pct": "5.00",
        "capital_pct": "5.00",
        "nonrecourse_beginning": "574,900",
        "nonrecourse_ending": "543,760",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "637,000",
        "capital_contributed": "0",
        "capital_net_income": "(84,630)",
        "capital_withdrawals": "(36,000)",
        "capital_ending": "516,370",
        "box1_ordinary_income": "",
        "box2_rental_real_estate": "(84,630)",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "3,680",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "12,400",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "",
        "box18c_nondeductible": "C  1,750",
        "box19a_distributions": "A  36,000",
        "box20a_investment_income": "3,680",
        "box20b_investment_expenses": "",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # PROFILE 12 — Sunbelt Retail Real Estate Fund II, LP
    # GP entity for the same partnership (EIN 46-3819204).
    # Tests A4 (capital consistency), A5 (partnership identity).
    # =========================================================================
    {
        "profile_number": 12,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Sunbelt Retail Real Estate Fund II, LP",
        "partnership_address": "3200 Southwest Freeway, Suite 1800\nHouston, TX 77027",
        "irs_center": "Ogden, UT",
        "ein": "46-3819204",
        "partner_name": "Sunbelt Capital GP, LLC",
        "partner_address": "3200 Southwest Freeway, Suite 1800\nHouston, TX 77027",
        "ssn": "46-9127538",
        "is_general_partner": True,
        "entity_type": "LLC",
        "profit_pct": "1.00",
        "loss_pct": "1.00",
        "capital_pct": "1.00",
        "nonrecourse_beginning": "114,980",
        "nonrecourse_ending": "108,752",
        "recourse_beginning": "85,000",
        "recourse_ending": "85,000",
        "capital_beginning": "127,400",
        "capital_contributed": "0",
        "capital_net_income": "(16,926)",
        "capital_withdrawals": "(7,200)",
        "capital_ending": "103,274",
        "box1_ordinary_income": "",
        "box2_rental_real_estate": "(16,926)",
        "box4a_guaranteed_services": "75,000",
        "box4c_total_guaranteed": "75,000",
        "box5_interest": "736",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "2,480",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  58,074",
        "box14c_gross_nonfarm": "C  58,074",
        "box17a_amt": "",
        "box18c_nondeductible": "C  350",
        "box19a_distributions": "A  7,200",
        "box20a_investment_income": "736",
        "box20b_investment_expenses": "",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # PROFILE 13 — Pacific Coast Orthopedic Partners, LLP
    # Second GP physician (EIN 86-3091745, same as Profile 7).
    # Brings percentage sum to 33.34% (16.67 + 16.67).
    # =========================================================================
    {
        "profile_number": 13,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Pacific Coast Orthopedic Partners, LLP",
        "partnership_address": "2250 East Camelback Road, Suite 450\nPhoenix, AZ 85016",
        "irs_center": "Ogden, UT",
        "ein": "86-3091745",
        "partner_name": "Dr. Alan R. Thompson",
        "partner_address": "3421 North 44th Street, Unit 8\nPhoenix, AZ 85018",
        "ssn": "528-63-4107",
        "is_general_partner": True,
        "entity_type": "Individual",
        "profit_pct": "16.67",
        "loss_pct": "16.67",
        "capital_pct": "16.67",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "48,500",
        "recourse_ending": "41,200",
        "capital_beginning": "305,200",
        "capital_contributed": "25,000",
        "capital_net_income": "198,440",
        "capital_withdrawals": "(180,000)",
        "capital_ending": "348,640",
        "box1_ordinary_income": "148,440",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "120,000",
        "box4c_total_guaranteed": "120,000",
        "box5_interest": "2,810",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "8,340",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  268,440",
        "box14c_gross_nonfarm": "C  268,440",
        "box17a_amt": "",
        "box18c_nondeductible": "C  4,200",
        "box19a_distributions": "A  180,000",
        "box20a_investment_income": "",
        "box20b_investment_expenses": "",
        "box20z_qbi": "Z  148,440",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # PROFILE 14 — Pacific Coast Orthopedic Partners, LLP
    # INVALID partner with 85.00% — triggers A1 critical failure.
    # Sum = 16.67 + 16.67 + 85.00 = 118.34% > 100%
    # EIN 86-3091745 (same as Profiles 7 and 13).
    # =========================================================================
    {
        "profile_number": 14,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Pacific Coast Orthopedic Partners, LLP",
        "partnership_address": "2250 East Camelback Road, Suite 450\nPhoenix, AZ 85016",
        "irs_center": "Ogden, UT",
        "ein": "86-3091745",
        "partner_name": "Dr. Sofia M. Reyes",
        "partner_address": "7100 East Indian School Road, Suite 210\nScottsdale, AZ 85251",
        "ssn": "604-21-8935",
        "is_general_partner": True,
        "entity_type": "Individual",
        "profit_pct": "85.00",
        "loss_pct": "85.00",
        "capital_pct": "85.00",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "247,500",
        "recourse_ending": "210,200",
        "capital_beginning": "1,558,000",
        "capital_contributed": "0",
        "capital_net_income": "1,011,600",
        "capital_withdrawals": "(950,000)",
        "capital_ending": "1,619,600",
        "box1_ordinary_income": "756,600",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "350,000",
        "box4c_total_guaranteed": "350,000",
        "box5_interest": "14,340",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "42,500",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  1,106,600",
        "box14c_gross_nonfarm": "C  1,106,600",
        "box17a_amt": "",
        "box18c_nondeductible": "C  21,420",
        "box19a_distributions": "A  950,000",
        "box20a_investment_income": "",
        "box20b_investment_expenses": "",
        "box20z_qbi": "Z  756,600",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # PROFILE 15 — Sunbelt Retail Real Estate Fund II, LP — 2023
    # Prior-year K-1 for Margaret L. Okonkwo (same as Profile 1, but 2023).
    # VALID B1: ending 2023 = $318,500 = beginning 2024 ($318,500 in Profile 1).
    # =========================================================================
    {
        "profile_number": 15,
        "tax_year": "2023",
        "form_version": "2023",
        "partnership_name": "Sunbelt Retail Real Estate Fund II, LP",
        "partnership_address": "3200 Southwest Freeway, Suite 1800\nHouston, TX 77027",
        "irs_center": "Ogden, UT",
        "ein": "46-3819204",
        "partner_name": "Margaret L. Okonkwo",
        "partner_address": "5412 Inwood Road\nDallas, TX 75209",
        "ssn": "621-47-8830",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "2.50",
        "loss_pct": "2.50",
        "capital_pct": "2.50",
        "nonrecourse_beginning": "302,100",
        "nonrecourse_ending": "287,450",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "345,800",
        "capital_contributed": "0",
        "capital_net_income": "(12,300)",
        "capital_withdrawals": "(15,000)",
        "capital_ending": "318,500",
        "box1_ordinary_income": "",
        "box2_rental_real_estate": "(12,300)",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "1,420",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "4,800",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "",
        "box18c_nondeductible": "C  650",
        "box19a_distributions": "A  15,000",
        "box20a_investment_income": "1,420",
        "box20b_investment_expenses": "",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # PROFILE 16 — Granite Peak Venture Partners III, LP — 2023
    # Prior-year K-1 for Priya R. Nambiar (same as Profile 2, but 2023).
    # INVALID B1: ending 2023 = $1,100,000 ≠ beginning 2024 = $1,284,700
    # (Profile 2 has capital_beginning = $1,284,700).
    # =========================================================================
    {
        "profile_number": 16,
        "tax_year": "2023",
        "form_version": "2023",
        "partnership_name": "Granite Peak Venture Partners III, LP",
        "partnership_address": "4100 Bohannon Drive, Suite 240\nMenlo Park, CA 94025",
        "irs_center": "Ogden, UT",
        "ein": "81-2047563",
        "partner_name": "Priya R. Nambiar",
        "partner_address": "725 Forest Avenue\nPalo Alto, CA 94301",
        "ssn": "549-82-1173",
        "is_general_partner": True,
        "entity_type": "Individual",
        "profit_pct": "20.00",
        "loss_pct": "20.00",
        "capital_pct": "1.00",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "145,000",
        "recourse_ending": "145,000",
        "capital_beginning": "980,400",
        "capital_contributed": "0",
        "capital_net_income": "419,600",
        "capital_withdrawals": "(300,000)",
        "capital_ending": "1,100,000",
        "box1_ordinary_income": "82,400",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "340,000",
        "box4c_total_guaranteed": "340,000",
        "box5_interest": "11,800",
        "box6a_ordinary_dividends": "6,200",
        "box6b_qualified_dividends": "4,900",
        "box8_st_capital_gain": "15,600",
        "box9a_lt_capital_gain": "412,000",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  422,400",
        "box14c_gross_nonfarm": "C  422,400",
        "box17a_amt": "A  (14,200)",
        "box18c_nondeductible": "C  1,800",
        "box19a_distributions": "A  300,000",
        "box20a_investment_income": "11,800",
        "box20b_investment_expenses": "5,400",
        "box20z_qbi": "Z  82,400",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # PROFILE 17 — Stonebridge Offshore Macro Fund, LP — 2023
    # Prior-year K-1 for Theodore J. Vanhanen (same as Profile 3, but 2023).
    # VALID B1: ending 2023 = $148,200 = beginning 2024 ($148,200 in Profile 3).
    # INVALID B4: was GP in 2023 but LP in 2024 → type change warning.
    # =========================================================================
    {
        "profile_number": 17,
        "tax_year": "2023",
        "form_version": "2023",
        "partnership_name": "Stonebridge Offshore Macro Fund, LP",
        "partnership_address": "601 Brickell Key Drive, Suite 700\nMiami, FL 33131",
        "irs_center": "Kansas City, MO",
        "ein": "27-6534891",
        "partner_name": "Theodore J. Vanhanen",
        "partner_address": "14 Harbour Court\nGreenwich, CT 06830",
        "ssn": "071-56-4422",
        "is_general_partner": True,
        "entity_type": "Individual",
        "profit_pct": "0.75",
        "loss_pct": "0.75",
        "capital_pct": "0.75",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "25,000",
        "recourse_ending": "0",
        "capital_beginning": "162,500",
        "capital_contributed": "0",
        "capital_net_income": "(14,300)",
        "capital_withdrawals": "0",
        "capital_ending": "148,200",
        "box1_ordinary_income": "(14,300)",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "12,400",
        "box6a_ordinary_dividends": "2,800",
        "box6b_qualified_dividends": "1,200",
        "box8_st_capital_gain": "(52,100)",
        "box9a_lt_capital_gain": "8,200",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  (14,300)",
        "box14c_gross_nonfarm": "C  (14,300)",
        "box17a_amt": "",
        "box18c_nondeductible": "C  380",
        "box19a_distributions": "",
        "box20a_investment_income": "15,200",
        "box20b_investment_expenses": "8,900",
        "box20z_qbi": "",
        "box21_foreign_taxes": "1,240",
    },

    # =========================================================================
    # PROFILE 18 — Sunbelt Retail Real Estate Fund II, LP — 2023
    # Prior-year K-1 for David K. Morales (same partner as Profile 11, 2023).
    # VALID B1: ending 2023 = $637,000 = beginning 2024 ($637,000 in Profile 11).
    # =========================================================================
    {
        "profile_number": 18,
        "tax_year": "2023",
        "form_version": "2023",
        "partnership_name": "Sunbelt Retail Real Estate Fund II, LP",
        "partnership_address": "3200 Southwest Freeway, Suite 1800\nHouston, TX 77027",
        "irs_center": "Ogden, UT",
        "ein": "46-3819204",
        "partner_name": "David K. Morales",
        "partner_address": "8901 Preston Road, Apt 2204\nDallas, TX 75225",
        "ssn": "453-18-7692",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "5.00",
        "loss_pct": "5.00",
        "capital_pct": "5.00",
        "nonrecourse_beginning": "604,200",
        "nonrecourse_ending": "574,900",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "692,400",
        "capital_contributed": "0",
        "capital_net_income": "(24,600)",
        "capital_withdrawals": "(30,800)",
        "capital_ending": "637,000",
        "box1_ordinary_income": "",
        "box2_rental_real_estate": "(24,600)",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "2,840",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "9,600",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "",
        "box18c_nondeductible": "C  1,200",
        "box19a_distributions": "A  30,800",
        "box20a_investment_income": "2,840",
        "box20b_investment_expenses": "",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # GROUP 4 — Additional partners for single-partner partnerships
    # Two additional partners for each of the 8 partnerships that previously
    # had only one partner in the records.
    # =========================================================================

    # --- Granite Peak Venture Partners III, LP (EIN 81-2047563) ---
    # Existing: Profile 2 (Nambiar, GP, 20.00%)

    # PROFILE 19 — Granite Peak LP investor
    {
        "profile_number": 19,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Granite Peak Venture Partners III, LP",
        "partnership_address": "4100 Bohannon Drive, Suite 240\nMenlo Park, CA 94025",
        "irs_center": "Ogden, UT",
        "ein": "81-2047563",
        "partner_name": "Elena J. Marchetti",
        "partner_address": "2800 Sand Hill Road, Suite 120\nMenlo Park, CA 94025",
        "ssn": "572-34-8816",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "8.00",
        "loss_pct": "8.00",
        "capital_pct": "8.00",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "514,000",
        "capital_contributed": "0",
        "capital_net_income": "356,940",
        "capital_withdrawals": "(180,000)",
        "capital_ending": "690,940",
        "box1_ordinary_income": "51,046",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "5,688",
        "box6a_ordinary_dividends": "3,376",
        "box6b_qualified_dividends": "2,712",
        "box8_st_capital_gain": "9,276",
        "box9a_lt_capital_gain": "296,354",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "A  (7,376)",
        "box18c_nondeductible": "C  940",
        "box19a_distributions": "A  180,000",
        "box20a_investment_income": "5,688",
        "box20b_investment_expenses": "2,720",
        "box20z_qbi": "Z  51,046",
        "box21_foreign_taxes": "",
    },

    # PROFILE 20 — Granite Peak LP (institutional)
    {
        "profile_number": 20,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Granite Peak Venture Partners III, LP",
        "partnership_address": "4100 Bohannon Drive, Suite 240\nMenlo Park, CA 94025",
        "irs_center": "Ogden, UT",
        "ein": "81-2047563",
        "partner_name": "Bay Area Endowment Fund",
        "partner_address": "555 California Street, 40th Floor\nSan Francisco, CA 94104",
        "ssn": "94-3182750",
        "is_general_partner": False,
        "entity_type": "Corporation",
        "profit_pct": "5.00",
        "loss_pct": "5.00",
        "capital_pct": "5.00",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "321,250",
        "capital_contributed": "0",
        "capital_net_income": "223,088",
        "capital_withdrawals": "(100,000)",
        "capital_ending": "444,338",
        "box1_ordinary_income": "31,904",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "3,555",
        "box6a_ordinary_dividends": "2,110",
        "box6b_qualified_dividends": "1,695",
        "box8_st_capital_gain": "5,798",
        "box9a_lt_capital_gain": "185,221",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "A  (4,610)",
        "box18c_nondeductible": "C  588",
        "box19a_distributions": "A  100,000",
        "box20a_investment_income": "3,555",
        "box20b_investment_expenses": "1,700",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # --- Stonebridge Offshore Macro Fund, LP (EIN 27-6534891) ---
    # Existing: Profile 3 (Vanhanen, LP, 0.75%)

    # PROFILE 21 — Stonebridge GP (fund manager entity)
    {
        "profile_number": 21,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Stonebridge Offshore Macro Fund, LP",
        "partnership_address": "601 Brickell Key Drive, Suite 700\nMiami, FL 33131",
        "irs_center": "Kansas City, MO",
        "ein": "27-6534891",
        "partner_name": "Stonebridge Capital Management, LLC",
        "partner_address": "601 Brickell Key Drive, Suite 700\nMiami, FL 33131",
        "ssn": "27-8941352",
        "is_general_partner": True,
        "entity_type": "LLC",
        "profit_pct": "15.00",
        "loss_pct": "15.00",
        "capital_pct": "1.00",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "250,000",
        "recourse_ending": "250,000",
        "capital_beginning": "2,964,000",
        "capital_contributed": "0",
        "capital_net_income": "(634,800)",
        "capital_withdrawals": "(480,000)",
        "capital_ending": "1,849,200",
        "box1_ordinary_income": "(634,800)",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "900,000",
        "box4c_total_guaranteed": "900,000",
        "box5_interest": "378,100",
        "box6a_ordinary_dividends": "82,300",
        "box6b_qualified_dividends": "37,400",
        "box8_st_capital_gain": "(1,746,600)",
        "box9a_lt_capital_gain": "248,800",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  265,200",
        "box14c_gross_nonfarm": "C  265,200",
        "box17a_amt": "",
        "box18c_nondeductible": "C  10,800",
        "box19a_distributions": "A  480,000",
        "box20a_investment_income": "460,400",
        "box20b_investment_expenses": "227,000",
        "box20z_qbi": "",
        "box21_foreign_taxes": "32,560",
    },

    # PROFILE 22 — Stonebridge LP investor
    {
        "profile_number": 22,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Stonebridge Offshore Macro Fund, LP",
        "partnership_address": "601 Brickell Key Drive, Suite 700\nMiami, FL 33131",
        "irs_center": "Kansas City, MO",
        "ein": "27-6534891",
        "partner_name": "Constance M. Hargrove",
        "partner_address": "41 Harbor Drive, Apt 18C\nStamford, CT 06902",
        "ssn": "042-78-3391",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "2.00",
        "loss_pct": "2.00",
        "capital_pct": "2.00",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "395,200",
        "capital_contributed": "200,000",
        "capital_net_income": "(84,640)",
        "capital_withdrawals": "0",
        "capital_ending": "510,560",
        "box1_ordinary_income": "(84,640)",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "50,413",
        "box6a_ordinary_dividends": "10,973",
        "box6b_qualified_dividends": "4,987",
        "box8_st_capital_gain": "(232,880)",
        "box9a_lt_capital_gain": "33,173",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "",
        "box18c_nondeductible": "C  1,440",
        "box19a_distributions": "",
        "box20a_investment_income": "61,387",
        "box20b_investment_expenses": "30,267",
        "box20z_qbi": "",
        "box21_foreign_taxes": "4,341",
    },

    # --- Ironclad Industrial Buyout Fund IV, LP (EIN 83-1726450) ---
    # Existing: Profile 4 (Callahan, LP, 5.25%)

    # PROFILE 23 — Ironclad LP investor
    {
        "profile_number": 23,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Ironclad Industrial Buyout Fund IV, LP",
        "partnership_address": "750 Seventh Avenue, 21st Floor\nNew York, NY 10019",
        "irs_center": "Ogden, UT",
        "ein": "83-1726450",
        "partner_name": "Patricia W. Davenport",
        "partner_address": "1040 Park Avenue, Apt 12B\nNew York, NY 10028",
        "ssn": "132-45-7803",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "3.75",
        "loss_pct": "3.75",
        "capital_pct": "3.75",
        "nonrecourse_beginning": "374,286",
        "nonrecourse_ending": "0",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "2,743,714",
        "capital_contributed": "0",
        "capital_net_income": "1,562,600",
        "capital_withdrawals": "(1,071,429)",
        "capital_ending": "3,234,886",
        "box1_ordinary_income": "62,600",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "22,986",
        "box6a_ordinary_dividends": "15,250",
        "box6b_qualified_dividends": "15,250",
        "box8_st_capital_gain": "(10,157)",
        "box9a_lt_capital_gain": "1,500,000",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "A  (27,000)",
        "box18c_nondeductible": "C  3,000",
        "box19a_distributions": "A  1,071,429",
        "box20a_investment_income": "22,986",
        "box20b_investment_expenses": "13,393",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # PROFILE 24 — Ironclad GP entity
    {
        "profile_number": 24,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Ironclad Industrial Buyout Fund IV, LP",
        "partnership_address": "750 Seventh Avenue, 21st Floor\nNew York, NY 10019",
        "irs_center": "Ogden, UT",
        "ein": "83-1726450",
        "partner_name": "Ironclad Capital Partners, LLC",
        "partner_address": "750 Seventh Avenue, 21st Floor\nNew York, NY 10019",
        "ssn": "83-2918470",
        "is_general_partner": True,
        "entity_type": "LLC",
        "profit_pct": "1.00",
        "loss_pct": "1.00",
        "capital_pct": "1.00",
        "nonrecourse_beginning": "99,810",
        "nonrecourse_ending": "0",
        "recourse_beginning": "180,000",
        "recourse_ending": "180,000",
        "capital_beginning": "731,657",
        "capital_contributed": "0",
        "capital_net_income": "416,693",
        "capital_withdrawals": "(285,714)",
        "capital_ending": "862,636",
        "box1_ordinary_income": "16,693",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "240,000",
        "box4c_total_guaranteed": "240,000",
        "box5_interest": "6,130",
        "box6a_ordinary_dividends": "4,067",
        "box6b_qualified_dividends": "4,067",
        "box8_st_capital_gain": "(2,709)",
        "box9a_lt_capital_gain": "400,000",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  256,693",
        "box14c_gross_nonfarm": "C  256,693",
        "box17a_amt": "A  (7,200)",
        "box18c_nondeductible": "C  800",
        "box19a_distributions": "A  285,714",
        "box20a_investment_income": "6,130",
        "box20b_investment_expenses": "3,571",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # --- Red Mesa Royalties & Exploration Partners, LP (EIN 75-2893041) ---
    # Existing: Profile 5 (Whitacre, GP, 15.00%)

    # PROFILE 25 — Red Mesa LP (working interest investor)
    {
        "profile_number": 25,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Red Mesa Royalties & Exploration Partners, LP",
        "partnership_address": "500 W. Texas Avenue, Suite 1200\nMidland, TX 79701",
        "irs_center": "Ogden, UT",
        "ein": "75-2893041",
        "partner_name": "Leland T. Crutcher",
        "partner_address": "4715 Andrews Highway\nOdessa, TX 79762",
        "ssn": "455-62-8104",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "10.00",
        "loss_pct": "10.00",
        "capital_pct": "10.00",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "275,000",
        "recourse_ending": "258,000",
        "capital_beginning": "594,867",
        "capital_contributed": "0",
        "capital_net_income": "209,853",
        "capital_withdrawals": "(80,000)",
        "capital_ending": "724,720",
        "box1_ordinary_income": "129,853",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "3,747",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "25,600",
        "box12_section_179": "15,000",
        "box13_other_deductions": "44,893",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "A  (19,100)",
        "box18c_nondeductible": "C  1,260",
        "box19a_distributions": "A  80,000",
        "box20a_investment_income": "3,747",
        "box20b_investment_expenses": "",
        "box20z_qbi": "Z  129,853",
        "box21_foreign_taxes": "2,143",
    },

    # PROFILE 26 — Red Mesa LP (triggers D1: distributions 4x income)
    {
        "profile_number": 26,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Red Mesa Royalties & Exploration Partners, LP",
        "partnership_address": "500 W. Texas Avenue, Suite 1200\nMidland, TX 79701",
        "irs_center": "Ogden, UT",
        "ein": "75-2893041",
        "partner_name": "Sarah K. Fontaine",
        "partner_address": "211 North Colorado Street\nMidland, TX 79701",
        "ssn": "451-90-3372",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "8.00",
        "loss_pct": "8.00",
        "capital_pct": "8.00",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "220,000",
        "recourse_ending": "206,400",
        "capital_beginning": "475,893",
        "capital_contributed": "0",
        "capital_net_income": "12,740",
        "capital_withdrawals": "(180,000)",
        "capital_ending": "308,633",
        "box1_ordinary_income": "12,740",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "2,998",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "12,000",
        "box13_other_deductions": "35,914",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "A  (15,280)",
        "box18c_nondeductible": "C  1,008",
        "box19a_distributions": "A  180,000",
        "box20a_investment_income": "2,998",
        "box20b_investment_expenses": "",
        "box20z_qbi": "Z  12,740",
        "box21_foreign_taxes": "1,714",
    },

    # --- Nakamura Family Investment LLC (EIN 93-2847561) ---
    # Existing: Profile 6 (Trust, LP, 22.50%)

    # PROFILE 27 — Nakamura LP (second family member)
    {
        "profile_number": 27,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Nakamura Family Investment LLC",
        "partnership_address": "7821 SW Barbur Boulevard, Suite 310\nPortland, OR 97219",
        "irs_center": "Ogden, UT",
        "ein": "93-2847561",
        "partner_name": "Yuki Nakamura",
        "partner_address": "1288 NW Everett Street, Unit 501\nPortland, OR 97209",
        "ssn": "543-81-2947",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "22.50",
        "loss_pct": "22.50",
        "capital_pct": "22.50",
        "nonrecourse_beginning": "14,200",
        "nonrecourse_ending": "11,800",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "87,400",
        "capital_contributed": "0",
        "capital_net_income": "(19,315)",
        "capital_withdrawals": "0",
        "capital_ending": "68,085",
        "box1_ordinary_income": "(19,315)",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "1,240",
        "box6a_ordinary_dividends": "3,180",
        "box6b_qualified_dividends": "2,750",
        "box8_st_capital_gain": "(4,620)",
        "box9a_lt_capital_gain": "6,890",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "A  (1,840)",
        "box18c_nondeductible": "",
        "box19a_distributions": "",
        "box20a_investment_income": "4,420",
        "box20b_investment_expenses": "1,875",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # PROFILE 28 — Nakamura GP (managing member)
    {
        "profile_number": 28,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Nakamura Family Investment LLC",
        "partnership_address": "7821 SW Barbur Boulevard, Suite 310\nPortland, OR 97219",
        "irs_center": "Ogden, UT",
        "ein": "93-2847561",
        "partner_name": "Kenji Nakamura",
        "partner_address": "4455 NE Fremont Street\nPortland, OR 97213",
        "ssn": "543-19-6738",
        "is_general_partner": True,
        "entity_type": "Individual",
        "profit_pct": "10.00",
        "loss_pct": "10.00",
        "capital_pct": "10.00",
        "nonrecourse_beginning": "6,311",
        "nonrecourse_ending": "5,244",
        "recourse_beginning": "15,000",
        "recourse_ending": "15,000",
        "capital_beginning": "38,844",
        "capital_contributed": "10,000",
        "capital_net_income": "(8,584)",
        "capital_withdrawals": "(6,000)",
        "capital_ending": "34,260",
        "box1_ordinary_income": "(8,584)",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "24,000",
        "box4c_total_guaranteed": "24,000",
        "box5_interest": "551",
        "box6a_ordinary_dividends": "1,413",
        "box6b_qualified_dividends": "1,222",
        "box8_st_capital_gain": "(2,053)",
        "box9a_lt_capital_gain": "3,062",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  15,416",
        "box14c_gross_nonfarm": "C  15,416",
        "box17a_amt": "A  (818)",
        "box18c_nondeductible": "",
        "box19a_distributions": "A  6,000",
        "box20a_investment_income": "1,964",
        "box20b_investment_expenses": "833",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # --- Sunbelt CRE Opportunity Fund III, LP (EIN 38-4702193) ---
    # Existing: Profile 8 (Oduya, LP, 4.80%)

    # PROFILE 29 — Sunbelt CRE LP investor
    {
        "profile_number": 29,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Sunbelt CRE Opportunity Fund III, LP",
        "partnership_address": "One Campus Martius, Suite 1800\nDetroit, MI 48226",
        "irs_center": "Ogden, UT",
        "ein": "38-4702193",
        "partner_name": "Denise A. Kowalski",
        "partner_address": "2900 West Maple Road, Suite 400\nTroy, MI 48084",
        "ssn": "381-64-9205",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "3.20",
        "loss_pct": "3.20",
        "capital_pct": "3.20",
        "nonrecourse_beginning": "274,667",
        "nonrecourse_ending": "265,667",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "1,226,667",
        "capital_contributed": "160,000",
        "capital_net_income": "(41,453)",
        "capital_withdrawals": "(32,000)",
        "capital_ending": "1,313,213",
        "box1_ordinary_income": "",
        "box2_rental_real_estate": "(41,453)",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "2,613",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "7,633",
        "box12_section_179": "59,733",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "A  (38,893)",
        "box18c_nondeductible": "",
        "box19a_distributions": "A  32,000",
        "box20a_investment_income": "2,613",
        "box20b_investment_expenses": "1,440",
        "box20z_qbi": "Z  (41,453)",
        "box21_foreign_taxes": "",
    },

    # PROFILE 30 — Sunbelt CRE GP entity
    {
        "profile_number": 30,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Sunbelt CRE Opportunity Fund III, LP",
        "partnership_address": "One Campus Martius, Suite 1800\nDetroit, MI 48226",
        "irs_center": "Ogden, UT",
        "ein": "38-4702193",
        "partner_name": "Sunbelt CRE Management, LLC",
        "partner_address": "One Campus Martius, Suite 1800\nDetroit, MI 48226",
        "ssn": "38-5190264",
        "is_general_partner": True,
        "entity_type": "LLC",
        "profit_pct": "1.50",
        "loss_pct": "1.50",
        "capital_pct": "1.50",
        "nonrecourse_beginning": "128,750",
        "nonrecourse_ending": "124,531",
        "recourse_beginning": "95,000",
        "recourse_ending": "95,000",
        "capital_beginning": "575,000",
        "capital_contributed": "0",
        "capital_net_income": "(19,431)",
        "capital_withdrawals": "(15,000)",
        "capital_ending": "540,569",
        "box1_ordinary_income": "",
        "box2_rental_real_estate": "(19,431)",
        "box4a_guaranteed_services": "120,000",
        "box4c_total_guaranteed": "120,000",
        "box5_interest": "1,225",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "3,578",
        "box12_section_179": "28,000",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  100,569",
        "box14c_gross_nonfarm": "C  100,569",
        "box17a_amt": "A  (18,231)",
        "box18c_nondeductible": "",
        "box19a_distributions": "A  15,000",
        "box20a_investment_income": "1,225",
        "box20b_investment_expenses": "675",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # --- Cascadia Clean Energy Fund LP (EIN 54-8031297) ---
    # Existing: Profile 9 (Commonwealth Corp, LP, 12.50%)

    # PROFILE 31 — Cascadia LP investor
    {
        "profile_number": 31,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Cascadia Clean Energy Fund LP",
        "partnership_address": "1760 Reston Parkway, Suite 600\nReston, VA 20190",
        "irs_center": "Ogden, UT",
        "ein": "54-8031297",
        "partner_name": "Green Horizon Capital, LLC",
        "partner_address": "1000 Wilson Boulevard, Suite 2700\nArlington, VA 22209",
        "ssn": "54-2836194",
        "is_general_partner": False,
        "entity_type": "LLC",
        "profit_pct": "8.00",
        "loss_pct": "8.00",
        "capital_pct": "8.00",
        "nonrecourse_beginning": "1,164,800",
        "nonrecourse_ending": "1,116,800",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "1,376,000",
        "capital_contributed": "320,000",
        "capital_net_income": "(248,077)",
        "capital_withdrawals": "0",
        "capital_ending": "1,447,923",
        "box1_ordinary_income": "(248,077)",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "5,594",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "A  (199,936)",
        "box18c_nondeductible": "C  9,280",
        "box19a_distributions": "",
        "box20a_investment_income": "5,594",
        "box20b_investment_expenses": "",
        "box20z_qbi": "Z  (248,077)",
        "box21_foreign_taxes": "30,323",
    },

    # PROFILE 32 — Cascadia LP (INVALID D4: LP with SE earnings)
    {
        "profile_number": 32,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Cascadia Clean Energy Fund LP",
        "partnership_address": "1760 Reston Parkway, Suite 600\nReston, VA 20190",
        "irs_center": "Ogden, UT",
        "ein": "54-8031297",
        "partner_name": "Raymond S. Holbrook",
        "partner_address": "8320 Leesburg Pike, Suite 210\nVienna, VA 22182",
        "ssn": "223-41-6758",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "6.00",
        "loss_pct": "6.00",
        "capital_pct": "6.00",
        "nonrecourse_beginning": "873,600",
        "nonrecourse_ending": "837,600",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "1,032,000",
        "capital_contributed": "240,000",
        "capital_net_income": "(186,058)",
        "capital_withdrawals": "0",
        "capital_ending": "1,085,942",
        "box1_ordinary_income": "(186,058)",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "4,195",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  (186,058)",
        "box14c_gross_nonfarm": "C  (186,058)",
        "box17a_amt": "A  (149,952)",
        "box18c_nondeductible": "C  6,960",
        "box19a_distributions": "",
        "box20a_investment_income": "4,195",
        "box20b_investment_expenses": "",
        "box20z_qbi": "Z  (186,058)",
        "box21_foreign_taxes": "22,743",
    },

    # --- Southern Hospitality Restaurant Group, LLC (EIN 58-2614039) ---
    # Existing: Profile 10 (Peach State Holdings, GP S-Corp, 35.00%)

    # PROFILE 33 — Southern Hospitality LP
    {
        "profile_number": 33,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Southern Hospitality Restaurant Group, LLC",
        "partnership_address": "3080 Peachtree Road NW, Suite 900\nAtlanta, GA 30305",
        "irs_center": "Ogden, UT",
        "ein": "58-2614039",
        "partner_name": "Angela D. Prescott",
        "partner_address": "2455 Paces Ferry Road, Apt 1210\nAtlanta, GA 30339",
        "ssn": "252-83-4190",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "25.00",
        "loss_pct": "25.00",
        "capital_pct": "25.00",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "44,571",
        "recourse_ending": "41,500",
        "capital_beginning": "10,714",
        "capital_contributed": "0",
        "capital_net_income": "20,675",
        "capital_withdrawals": "(12,857)",
        "capital_ending": "18,532",
        "box1_ordinary_income": "20,675",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "",
        "box18c_nondeductible": "",
        "box19a_distributions": "A  12,857",
        "box20a_investment_income": "",
        "box20b_investment_expenses": "",
        "box20z_qbi": "Z  20,675",
        "box21_foreign_taxes": "",
    },

    # PROFILE 34 — Southern Hospitality LP (sum=75% → A2 warning)
    {
        "profile_number": 34,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Southern Hospitality Restaurant Group, LLC",
        "partnership_address": "3080 Peachtree Road NW, Suite 900\nAtlanta, GA 30305",
        "irs_center": "Ogden, UT",
        "ein": "58-2614039",
        "partner_name": "William R. Tarkington",
        "partner_address": "785 Piedmont Avenue NE, Unit 3B\nAtlanta, GA 30308",
        "ssn": "258-47-6021",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "15.00",
        "loss_pct": "15.00",
        "capital_pct": "15.00",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "26,743",
        "recourse_ending": "24,900",
        "capital_beginning": "6,429",
        "capital_contributed": "0",
        "capital_net_income": "12,405",
        "capital_withdrawals": "(7,714)",
        "capital_ending": "11,119",
        "box1_ordinary_income": "12,405",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "",
        "box18c_nondeductible": "",
        "box19a_distributions": "A  7,714",
        "box20a_investment_income": "",
        "box20b_investment_expenses": "",
        "box20z_qbi": "Z  12,405",
        "box21_foreign_taxes": "",
    },
]
