"""
Schedule K-1 cross-partner test profiles (Profiles 11-18).

Designed to exercise cross-partner and multi-year validation rules:

Group 1 — Same-partnership partners (Category A tests):
  11 -- Sunbelt Retail RE Fund II (2nd LP, 5.00%)
  12 -- Sunbelt Retail RE Fund II (GP, 1.00%)
  13 -- Pacific Coast Orthopedic Partners (2nd GP, 16.67%)
  14 -- Pacific Coast Orthopedic Partners (3rd GP, 85.00% — INVALID, triggers A1)

Group 2 — Prior-year K-1s (Category B tests):
  15 -- Sunbelt Retail RE Fund II, Okonkwo 2023 (valid B1 continuity)
  16 -- Granite Peak Venture III, Nambiar 2023 (invalid B1 — capital mismatch)
  17 -- Stonebridge Offshore Macro, Vanhanen 2023 (valid B1 + invalid B4 — GP→LP type change)

Group 3 — Edge cases:
  18 -- Sunbelt Retail RE Fund II, Morales 2023 (prior-year for Profile 11)

All EINs, SSNs, addresses, and financial figures are entirely fictitious.
"""

CROSS_PARTNER_PROFILES = [
    # =========================================================================
    # PROFILE 11 — Sunbelt Retail Real Estate Fund II, LP
    # Second LP in the same partnership as Profile 1 (Okonkwo).
    # Tests A2 (sum=8.50% < 100%), A3 (income proportionality).
    # EIN matches Profile 1: 46-3819204
    # =========================================================================
    {
        "profile_number": 11,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Sunbelt Retail Real Estate Fund II, LP",
        "partnership_address": "3200 Southwest Freeway, Suite 1800\nHouston, TX 77027",
        "irs_center": "Ogden, UT",
        "ein": "46-3819204",
        "partner_name": "David K. Morales",
        "partner_address": "8901 Preston Road, Apt 2204\nDallas, TX 75225",
        "ssn": "453-18-7692",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "5.00",
        "loss_pct": "5.00",
        "capital_pct": "5.00",
        "nonrecourse_beginning": "574,900",
        "nonrecourse_ending": "543,760",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "637,000",
        "capital_contributed": "0",
        "capital_net_income": "(84,630)",
        "capital_withdrawals": "(36,000)",
        "capital_ending": "516,370",
        "box1_ordinary_income": "",
        "box2_rental_real_estate": "(84,630)",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "3,680",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "12,400",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "",
        "box18c_nondeductible": "C  1,750",
        "box19a_distributions": "A  36,000",
        "box20a_investment_income": "3,680",
        "box20b_investment_expenses": "",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # PROFILE 12 — Sunbelt Retail Real Estate Fund II, LP
    # GP entity for the same partnership (EIN 46-3819204).
    # Tests A4 (capital consistency), A5 (partnership identity).
    # =========================================================================
    {
        "profile_number": 12,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Sunbelt Retail Real Estate Fund II, LP",
        "partnership_address": "3200 Southwest Freeway, Suite 1800\nHouston, TX 77027",
        "irs_center": "Ogden, UT",
        "ein": "46-3819204",
        "partner_name": "Sunbelt Capital GP, LLC",
        "partner_address": "3200 Southwest Freeway, Suite 1800\nHouston, TX 77027",
        "ssn": "46-9127538",
        "is_general_partner": True,
        "entity_type": "LLC",
        "profit_pct": "1.00",
        "loss_pct": "1.00",
        "capital_pct": "1.00",
        "nonrecourse_beginning": "114,980",
        "nonrecourse_ending": "108,752",
        "recourse_beginning": "85,000",
        "recourse_ending": "85,000",
        "capital_beginning": "127,400",
        "capital_contributed": "0",
        "capital_net_income": "(16,926)",
        "capital_withdrawals": "(7,200)",
        "capital_ending": "103,274",
        "box1_ordinary_income": "",
        "box2_rental_real_estate": "(16,926)",
        "box4a_guaranteed_services": "75,000",
        "box4c_total_guaranteed": "75,000",
        "box5_interest": "736",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "2,480",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  58,074",
        "box14c_gross_nonfarm": "C  58,074",
        "box17a_amt": "",
        "box18c_nondeductible": "C  350",
        "box19a_distributions": "A  7,200",
        "box20a_investment_income": "736",
        "box20b_investment_expenses": "",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # PROFILE 13 — Pacific Coast Orthopedic Partners, LLP
    # Second GP physician (EIN 86-3091745, same as Profile 7).
    # Brings percentage sum to 33.34% (16.67 + 16.67).
    # =========================================================================
    {
        "profile_number": 13,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Pacific Coast Orthopedic Partners, LLP",
        "partnership_address": "2250 East Camelback Road, Suite 450\nPhoenix, AZ 85016",
        "irs_center": "Ogden, UT",
        "ein": "86-3091745",
        "partner_name": "Dr. Alan R. Thompson",
        "partner_address": "3421 North 44th Street, Unit 8\nPhoenix, AZ 85018",
        "ssn": "528-63-4107",
        "is_general_partner": True,
        "entity_type": "Individual",
        "profit_pct": "16.67",
        "loss_pct": "16.67",
        "capital_pct": "16.67",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "48,500",
        "recourse_ending": "41,200",
        "capital_beginning": "305,200",
        "capital_contributed": "25,000",
        "capital_net_income": "198,440",
        "capital_withdrawals": "(180,000)",
        "capital_ending": "348,640",
        "box1_ordinary_income": "148,440",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "120,000",
        "box4c_total_guaranteed": "120,000",
        "box5_interest": "2,810",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "8,340",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  268,440",
        "box14c_gross_nonfarm": "C  268,440",
        "box17a_amt": "",
        "box18c_nondeductible": "C  4,200",
        "box19a_distributions": "A  180,000",
        "box20a_investment_income": "",
        "box20b_investment_expenses": "",
        "box20z_qbi": "Z  148,440",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # PROFILE 14 — Pacific Coast Orthopedic Partners, LLP
    # INVALID partner with 85.00% — triggers A1 critical failure.
    # Sum = 16.67 + 16.67 + 85.00 = 118.34% > 100%
    # EIN 86-3091745 (same as Profiles 7 and 13).
    # =========================================================================
    {
        "profile_number": 14,
        "tax_year": "2024",
        "form_version": "2024",
        "partnership_name": "Pacific Coast Orthopedic Partners, LLP",
        "partnership_address": "2250 East Camelback Road, Suite 450\nPhoenix, AZ 85016",
        "irs_center": "Ogden, UT",
        "ein": "86-3091745",
        "partner_name": "Dr. Sofia M. Reyes",
        "partner_address": "7100 East Indian School Road, Suite 210\nScottsdale, AZ 85251",
        "ssn": "604-21-8935",
        "is_general_partner": True,
        "entity_type": "Individual",
        "profit_pct": "85.00",
        "loss_pct": "85.00",
        "capital_pct": "85.00",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "247,500",
        "recourse_ending": "210,200",
        "capital_beginning": "1,558,000",
        "capital_contributed": "0",
        "capital_net_income": "1,011,600",
        "capital_withdrawals": "(950,000)",
        "capital_ending": "1,619,600",
        "box1_ordinary_income": "756,600",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "350,000",
        "box4c_total_guaranteed": "350,000",
        "box5_interest": "14,340",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "42,500",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  1,106,600",
        "box14c_gross_nonfarm": "C  1,106,600",
        "box17a_amt": "",
        "box18c_nondeductible": "C  21,420",
        "box19a_distributions": "A  950,000",
        "box20a_investment_income": "",
        "box20b_investment_expenses": "",
        "box20z_qbi": "Z  756,600",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # PROFILE 15 — Sunbelt Retail Real Estate Fund II, LP — 2023
    # Prior-year K-1 for Margaret L. Okonkwo (same as Profile 1, but 2023).
    # VALID B1: ending 2023 = $318,500 = beginning 2024 ($318,500 in Profile 1).
    # =========================================================================
    {
        "profile_number": 15,
        "tax_year": "2023",
        "form_version": "2023",
        "partnership_name": "Sunbelt Retail Real Estate Fund II, LP",
        "partnership_address": "3200 Southwest Freeway, Suite 1800\nHouston, TX 77027",
        "irs_center": "Ogden, UT",
        "ein": "46-3819204",
        "partner_name": "Margaret L. Okonkwo",
        "partner_address": "5412 Inwood Road\nDallas, TX 75209",
        "ssn": "621-47-8830",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "2.50",
        "loss_pct": "2.50",
        "capital_pct": "2.50",
        "nonrecourse_beginning": "302,100",
        "nonrecourse_ending": "287,450",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "345,800",
        "capital_contributed": "0",
        "capital_net_income": "(12,300)",
        "capital_withdrawals": "(15,000)",
        "capital_ending": "318,500",
        "box1_ordinary_income": "",
        "box2_rental_real_estate": "(12,300)",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "1,420",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "4,800",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "",
        "box18c_nondeductible": "C  650",
        "box19a_distributions": "A  15,000",
        "box20a_investment_income": "1,420",
        "box20b_investment_expenses": "",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # PROFILE 16 — Granite Peak Venture Partners III, LP — 2023
    # Prior-year K-1 for Priya R. Nambiar (same as Profile 2, but 2023).
    # INVALID B1: ending 2023 = $1,100,000 ≠ beginning 2024 = $1,284,700
    # (Profile 2 has capital_beginning = $1,284,700).
    # =========================================================================
    {
        "profile_number": 16,
        "tax_year": "2023",
        "form_version": "2023",
        "partnership_name": "Granite Peak Venture Partners III, LP",
        "partnership_address": "4100 Bohannon Drive, Suite 240\nMenlo Park, CA 94025",
        "irs_center": "Ogden, UT",
        "ein": "81-2047563",
        "partner_name": "Priya R. Nambiar",
        "partner_address": "725 Forest Avenue\nPalo Alto, CA 94301",
        "ssn": "549-82-1173",
        "is_general_partner": True,
        "entity_type": "Individual",
        "profit_pct": "20.00",
        "loss_pct": "20.00",
        "capital_pct": "1.00",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "145,000",
        "recourse_ending": "145,000",
        "capital_beginning": "980,400",
        "capital_contributed": "0",
        "capital_net_income": "419,600",
        "capital_withdrawals": "(300,000)",
        "capital_ending": "1,100,000",
        "box1_ordinary_income": "82,400",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "340,000",
        "box4c_total_guaranteed": "340,000",
        "box5_interest": "11,800",
        "box6a_ordinary_dividends": "6,200",
        "box6b_qualified_dividends": "4,900",
        "box8_st_capital_gain": "15,600",
        "box9a_lt_capital_gain": "412,000",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  422,400",
        "box14c_gross_nonfarm": "C  422,400",
        "box17a_amt": "A  (14,200)",
        "box18c_nondeductible": "C  1,800",
        "box19a_distributions": "A  300,000",
        "box20a_investment_income": "11,800",
        "box20b_investment_expenses": "5,400",
        "box20z_qbi": "Z  82,400",
        "box21_foreign_taxes": "",
    },

    # =========================================================================
    # PROFILE 17 — Stonebridge Offshore Macro Fund, LP — 2023
    # Prior-year K-1 for Theodore J. Vanhanen (same as Profile 3, but 2023).
    # VALID B1: ending 2023 = $148,200 = beginning 2024 ($148,200 in Profile 3).
    # INVALID B4: was GP in 2023 but LP in 2024 → type change warning.
    # =========================================================================
    {
        "profile_number": 17,
        "tax_year": "2023",
        "form_version": "2023",
        "partnership_name": "Stonebridge Offshore Macro Fund, LP",
        "partnership_address": "601 Brickell Key Drive, Suite 700\nMiami, FL 33131",
        "irs_center": "Kansas City, MO",
        "ein": "27-6534891",
        "partner_name": "Theodore J. Vanhanen",
        "partner_address": "14 Harbour Court\nGreenwich, CT 06830",
        "ssn": "071-56-4422",
        "is_general_partner": True,
        "entity_type": "Individual",
        "profit_pct": "0.75",
        "loss_pct": "0.75",
        "capital_pct": "0.75",
        "nonrecourse_beginning": "0",
        "nonrecourse_ending": "0",
        "recourse_beginning": "25,000",
        "recourse_ending": "0",
        "capital_beginning": "162,500",
        "capital_contributed": "0",
        "capital_net_income": "(14,300)",
        "capital_withdrawals": "0",
        "capital_ending": "148,200",
        "box1_ordinary_income": "(14,300)",
        "box2_rental_real_estate": "",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "12,400",
        "box6a_ordinary_dividends": "2,800",
        "box6b_qualified_dividends": "1,200",
        "box8_st_capital_gain": "(52,100)",
        "box9a_lt_capital_gain": "8,200",
        "box12_section_179": "",
        "box13_other_deductions": "",
        "box14a_se_earnings": "A  (14,300)",
        "box14c_gross_nonfarm": "C  (14,300)",
        "box17a_amt": "",
        "box18c_nondeductible": "C  380",
        "box19a_distributions": "",
        "box20a_investment_income": "15,200",
        "box20b_investment_expenses": "8,900",
        "box20z_qbi": "",
        "box21_foreign_taxes": "1,240",
    },

    # =========================================================================
    # PROFILE 18 — Sunbelt Retail Real Estate Fund II, LP — 2023
    # Prior-year K-1 for David K. Morales (same partner as Profile 11, 2023).
    # VALID B1: ending 2023 = $637,000 = beginning 2024 ($637,000 in Profile 11).
    # =========================================================================
    {
        "profile_number": 18,
        "tax_year": "2023",
        "form_version": "2023",
        "partnership_name": "Sunbelt Retail Real Estate Fund II, LP",
        "partnership_address": "3200 Southwest Freeway, Suite 1800\nHouston, TX 77027",
        "irs_center": "Ogden, UT",
        "ein": "46-3819204",
        "partner_name": "David K. Morales",
        "partner_address": "8901 Preston Road, Apt 2204\nDallas, TX 75225",
        "ssn": "453-18-7692",
        "is_general_partner": False,
        "entity_type": "Individual",
        "profit_pct": "5.00",
        "loss_pct": "5.00",
        "capital_pct": "5.00",
        "nonrecourse_beginning": "604,200",
        "nonrecourse_ending": "574,900",
        "recourse_beginning": "0",
        "recourse_ending": "0",
        "capital_beginning": "692,400",
        "capital_contributed": "0",
        "capital_net_income": "(24,600)",
        "capital_withdrawals": "(30,800)",
        "capital_ending": "637,000",
        "box1_ordinary_income": "",
        "box2_rental_real_estate": "(24,600)",
        "box4a_guaranteed_services": "",
        "box4c_total_guaranteed": "",
        "box5_interest": "2,840",
        "box6a_ordinary_dividends": "",
        "box6b_qualified_dividends": "",
        "box8_st_capital_gain": "",
        "box9a_lt_capital_gain": "",
        "box12_section_179": "9,600",
        "box13_other_deductions": "",
        "box14a_se_earnings": "",
        "box14c_gross_nonfarm": "",
        "box17a_amt": "",
        "box18c_nondeductible": "C  1,200",
        "box19a_distributions": "A  30,800",
        "box20a_investment_income": "2,840",
        "box20b_investment_expenses": "",
        "box20z_qbi": "",
        "box21_foreign_taxes": "",
    },
]
